/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EventsConfigurationSchema extends BaseModel {
  static $columns = ['createdAt', 'eventDescription', 'eventEndTime', 'eventName', 'eventStartTime', 'id', 'isActive', 'jackpotCombinations', 'prizeDetails', 'updatedAt'] as const
  $columns = EventsConfigurationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare eventDescription: string
  @column.dateTime()
  declare eventEndTime: DateTime
  @column()
  declare eventName: string
  @column.dateTime()
  declare eventStartTime: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare jackpotCombinations: string
  @column()
  declare prizeDetails: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserbetSchema extends BaseModel {
  static $columns = ['betAmount', 'betCombinationResult', 'createdAt', 'eventId', 'id', 'isJackpot', 'isWinner', 'updatedAt', 'userId'] as const
  $columns = UserbetSchema.$columns
  @column()
  declare betAmount: number | null
  @column()
  declare betCombinationResult: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare eventId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isJackpot: boolean | null
  @column()
  declare isWinner: boolean | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
